name: atdy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # 定时任务
    - cron: '30 2,13 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: 订阅脚本 #订阅脚本
      env: 
        GHCOOKIE: ${{ secrets.GHCOOKIE }} # secrets_id 提供
      run: | 
        python DingYue.py
    - name: Commit #上传到仓库
      run: |
        git config --global user.email lovesr11@outlook.com
        git config --global user.name lovesr11
        git add .
        git commit -m "update new Node.txt" -a
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
         branch: master   
